<template>
  <AppHeader></AppHeader>
  <main>
    <AppHero></AppHero>
    <AppSectionWhy></AppSectionWhy>
    <AppSectionVideo></AppSectionVideo>
    <AppSectionTeachers></AppSectionTeachers>
    <AppSectionWhat></AppSectionWhat>
  </main>
  <AppFooter></AppFooter>
</template>
